[toolchain]
target_profile = "x86_64-win64"

[build]
incremental = false
progress = true

[[assembly]]
name = "main"
kind = "executable"
root = "./Main"
out_dir = "build/main"
emit_ir = "ll"

[[assembly]]
name = "core"
kind = "dependency"
root = "./Core"
out_dir = "build/core"

[[assembly]]
name = "spec"
kind = "dependency"
root = "./Spec"
out_dir = "build/spec"

[[assembly]]
name = "reference"
kind = "dependency"
root = "./Reference"
out_dir = "build/reference"

[[assembly]]
name = "generators"
kind = "dependency"
root = "./Generators"
out_dir = "build/generators"

[[assembly]]
name = "runner"
kind = "dependency"
root = "./Runner"
out_dir = "build/runner"

[[assembly]]
name = "oracle"
kind = "dependency"
root = "./Oracle"
out_dir = "build/oracle"

[[assembly]]
name = "suites"
kind = "dependency"
root = "./Suites"
out_dir = "build/suites"
