[toolchain]
llvm_bin = "C:/Dev/Cursive/extern/llvm/llvm-21.1.8-x86_64/bin"

[[assembly]]
name = "main"
kind = "executable"
root = "."
out_dir = "build/main"
emit_ir = "ll"

[[assembly]]
name = "compiler"
kind = "dependency"
root = "./Compiler"
out_dir = "build/compiler"

[[assembly]]
name = "types"
kind = "dependency"
root = "./Types"
out_dir = "build/types"

[[assembly]]
name = "operations"
kind = "dependency"
root = "./Operations"
out_dir = "build/operations"

[[assembly]]
name = "memory"
kind = "dependency"
root = "./Memory"
out_dir = "build/memory"

[[assembly]]
name = "permissions"
kind = "dependency"
root = "./Permissions"
out_dir = "build/permissions"

[[assembly]]
name = "pointers"
kind = "dependency"
root = "./Pointers"
out_dir = "build/pointers"

[[assembly]]
name = "modals"
kind = "dependency"
root = "./Modals"
out_dir = "build/modals"

[[assembly]]
name = "contracts"
kind = "dependency"
root = "./Contracts"
out_dir = "build/contracts"

[[assembly]]
name = "attributes"
kind = "dependency"
root = "./Attributes"
out_dir = "build/attributes"

[[assembly]]
name = "concurrency"
kind = "dependency"
root = "./Concurrency"
out_dir = "build/concurrency"

[[assembly]]
name = "ffi"
kind = "dependency"
root = "./FFI"
out_dir = "build/ffi"

[[assembly]]
name = "linkedshareddep"
kind = "dependency"
root = "./LinkedSharedDep"
out_dir = "build/linkedshareddep"

[[assembly]]
name = "linkedshared"
kind = "library"
root = "./LinkedShared"
out_dir = "build/linkedshared"

[[assembly]]
name = "linkedstaticdep"
kind = "dependency"
root = "./LinkedStaticDep"
out_dir = "build/linkedstaticdep"

[[assembly]]
name = "linkedstatic"
kind = "library"
link_kind = "static"
root = "./LinkedStatic"
out_dir = "build/linkedstatic"

[[assembly]]
name = "hostedshareddep"
kind = "dependency"
root = "./HostedSharedDep"
out_dir = "build/hostedshareddep"

[[assembly]]
name = "hostedshared"
kind = "library"
root = "./HostedShared"
out_dir = "build/hostedshared"

[[assembly]]
name = "rawshared"
kind = "library"
root = "./RawShared"
out_dir = "build/rawshared"
