[toolchain]
target_profile = "x86_64-win64"

[build]
incremental = false
progress = true

[[assembly]]
name = "main"
kind = "executable"
root = "./Main"
out_dir = "build/main"
emit_ir = "ll"

[[assembly]]
name = "oracle_main"
kind = "executable"
root = "./Oracle/Main"
out_dir = "build/oracle"
emit_ir = "ll"

[[assembly]]
name = "core"
kind = "dependency"
root = "./Oracle/Core"
out_dir = "build/oracle-core"

[[assembly]]
name = "spec"
kind = "dependency"
root = "./Oracle/Spec"
out_dir = "build/oracle-spec"

[[assembly]]
name = "runner"
kind = "dependency"
root = "./Oracle/Runner"
out_dir = "build/oracle-runner"

[[assembly]]
name = "compare"
kind = "dependency"
root = "./Oracle/Compare"
out_dir = "build/oracle-compare"

[[assembly]]
name = "coverage"
kind = "dependency"
root = "./Oracle/Coverage"
out_dir = "build/oracle-coverage"

[[assembly]]
name = "suites"
kind = "dependency"
root = "./Oracle/Suites"
out_dir = "build/oracle-suites"
