[toolchain]
target_profile = "x86_64-win64"

[build]
incremental = false
progress = false

[[assembly]]
name = "MinimalExecutable"
kind = "executable"
root = "./Main"
out_dir = "build/main"
emit_ir = "ll"
